version: '3.9'
services:
 db:
    image: postgres
    container_name: db
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
 django:
    build: .
    command: python manage.py runserver 0.0.0.0:5000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=127.0.0.1
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKERND=redis://redis:6379/0
    depends_on:
      - db
      - redis
 celery:
    build: .
    volumes:
      - .:/code
    command: celery -A tasks worker -l info
    depends_on:
      - redis
      - django
 redis:
      image: redis:alpine
      volumes:
        - ./redis.conf:/usr/local/etc/redis/redis.conf
      ports:
        - "6379"
