# Generated by Django 4.2.3 on 2023-10-12 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EpisodeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('itunes_author', models.CharField(blank=True, default='Unknown', max_length=100, null=True)),
                ('itunes_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('images', models.TextField(default='image url')),
                ('guid', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LikeEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RSSLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PodcastData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('itunes_author', models.CharField(blank=True, default='Unknown', max_length=100, null=True)),
                ('itunes_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('images', models.TextField(default='image url')),
                ('rss_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rss_parser.rsslink')),
            ],
        ),
        migrations.CreateModel(
            name='LikePodcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rss_parser.podcastdata')),
            ],
        ),
    ]
