# Generated by Django 4.2.5 on 2023-09-27 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss_parser', '0003_like_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelparser',
            old_name='author',
            new_name='itunes_author',
        ),
        migrations.RenameField(
            model_name='modelparser',
            old_name='duration',
            new_name='itunes_duration',
        ),
    ]
