# Generated by Django 4.2.5 on 2023-09-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_parser', '0004_rename_author_modelparser_itunes_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelparser',
            name='itunes_author',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True),
        ),
    ]
