# Generated by Django 4.2.5 on 2023-09-29 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_parser', '0009_alter_like_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelparser',
            name='category',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
