# Generated by Django 4.2.5 on 2023-09-29 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss_parser', '0010_modelparser_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='title',
            new_name='category',
        ),
    ]
