# Generated by Django 4.2.5 on 2023-09-29 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss_parser', '0011_rename_title_like_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='category',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='modelparser',
            name='category',
        ),
    ]
