
services:

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    networks:
      - main
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq
    restart: always

  # postgres:
  #   container_name: postgres
  #   image: postgres:14.0
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: 3858nima
  #     POSTGRES_DB: final_pro
  #   networks:
  #     - main
  #   ports:
  #     - 5432:5432
  #   restart: always
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: app
    volumes:
      - .:/code
    networks:
      - main
    depends_on:
      # - postgres
      - redis
    ports:
      - 8000:8000
    restart: always

  redis:
    container_name: redis
    image: redis:7.2
    networks:
      - main
    volumes:
      - redis_data:/data

  celery:
    container_name: celery
    build: .
    command: celery -A podcast_manager worker  --loglevel=info
    depends_on:
      - redis
      - app
    environment:
      - C_FORCE_ROOT="true"
    networks:
      - main
    restart: always
    volumes:
      - .:/code

  celerybeat:
    restart: always
    build: .
    volumes:
      - .:/code
    command: celery -A podcast_manager beat -l INFO
    networks:
      - main
    depends_on:
      - celery

  login_consumer:
    container_name: login_consumer
    command: python3 manage.py login_listener
    build: .
    restart: always
    networks:
      - main
    volumes:
      - .:/code
    depends_on:
      - rabbitmq
      - app

  update_invalid_podcast_consumer:
    container_name: update_invalid_podcast_consumer
    command: python3 manage.py update_invalid_podcast_listener
    build: .
    restart: always
    networks:
      - main
    volumes:
      - .:/code
    depends_on:
      - rabbitmq
      - app

  register_consumer:
    container_name: register_consumer
    command: python3 manage.py register_listener
    build: .
    restart: always
    networks:
      - main
    volumes:
      - .:/code
    depends_on:
      - rabbitmq
      - app

  update_valid_podcast_consumer:
    container_name: update_valid_podcast_consumer
    command: python3 manage.py update_valid_podcast_listener
    build: .
    restart: always
    networks:
      - main
    volumes:
      - .:/code
    depends_on:
      - rabbitmq
      - app


networks:
  main:

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
  rabbitmq_log:

