# Generated by Django 4.2.5 on 2023-09-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_parser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelparser',
            name='author',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='modelparser',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='modelparser',
            name='images',
            field=models.TextField(default='image url'),
        ),
    ]
