# Generated by Django 4.2.5 on 2023-09-28 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss_parser', '0006_alter_like_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='podcast',
            new_name='title',
        ),
    ]
