# Generated by Django 4.2.5 on 2023-09-29 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rss_parser', '0008_alter_like_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rss_parser.modelparser'),
        ),
    ]
