# Generated by Django 4.2.5 on 2023-09-29 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_parser', '0012_rename_category_like_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelparser',
            name='id',
        ),
        migrations.AlterField(
            model_name='modelparser',
            name='title',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
